import { app, BrowserWindow } from "electron";
import log from "electron-log/main";
import { FileDownloader } from "./main/file-downloader/FileDownloader";
import { GameLauncher } from "./main/game-launcher/GameLauncher";
import { UZDoomDownloader } from "./main/uzdoom-downloader";

log.initialize();
log.transports.file.format =
	"[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [{processType}] [{level}] {scope} {text}";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
	app.quit();
}

const downloader = new FileDownloader();
const uzDoomDownloader = new UZDoomDownloader(downloader.download);
const gameLauncher = new GameLauncher();

const createWindow = (): void => {
	const mainWindow = new BrowserWindow({
		height: 640,
		width: 1024,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
		},
	});

	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
	uzDoomDownloader.registerHandler(mainWindow);

	// mainWindow.webContents.openDevTools();
};

app.whenReady().then(async () => {
	createWindow();
	gameLauncher.registerHandler();
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
// app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
	if (process.platform !== "darwin") {
		app.quit();
	}
});

app.on("activate", () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});
